### PR TITLE
Changed maps service from google maps to leaflet

### PR DESCRIPTION
**Pull request by kalsmic**
@BrunoNicholas, @ringtho,@brucenelm,@Phionanamugga
Kindly review and give feedback. I have switched to using Leaflet instead of the google maps API because my credit for the Google maps API key is done and was not able to renew it at the moment. I tried adding the credit card for Centenary bank but it failed to verify. I also tried using an MTN momo card but in vain.

### CODE REVIEW

**Comment by BrunoNicholas** [comment]
Great, it is clean and no conflicts, let me go through the ```gh-pages``` via the links and see-through!

**Comment by kalsmic** [comment]
Thanks, @BrunoNicholas. On the lookout for more feedback

**Comment by ghost** [comment]
I think its ok, maybe just try making the colors more user friendly

**Comment by kalsmic** [comment]
> I think its ok, maybe just try making the colors more user friendly

Thanks, @Phionanamugga.  what do you mean by user-friendly,? Are they too dull or too bright? Kindly enlight me on this.

**Pull request merged**
