### PR TITLE
Integrate complete UI pages into develop

### PR DESCRIPTION
**Pull request by kalsmic**
Kindly review my UI templates and source code and give feedback.
  I also await your feedback on but not limited to
 - best practices 
 - Git workflow
 - Responsive design.

@HabibSentongo,@MukuruH,@dtnnml,@kyakusahmed,@PatrickMugayaJoel,@Manorlds-Eaglespark

### CODE REVIEW

**Comment by KapsonLabs** [comment]
Clean UI, Flawless Git Workflow. 
Have 2 comments to make about ur UI.
 
1. Please have the footer stick to the bottom on the login page.
2. On Mobile view, Have a better way of representing the side bar. Its taking up too much view space and always appears. It may be unnecessary for it to always appear.

**Comment by kalsmic** [comment]
Thanks, @KapsonLabs.  Let me fix the footer and also redesign my sidebar.
I am going to hide it on mobile devices and button the user can click to see it.

**Comment by KapsonLabs** [comment]
Excellent.

**Comment by davicken** [comment]
My man @kalsmic  that's some great work there. only that i think  you should let your footer persist or appear on all your web pages at the extreme bottom of your content. Cheers

**Comment by bakersen** [comment]
It's a good UI. Looks like there's extra margins around your body. (white space) It could be my browser but can just add * {margin: 0;} such that it's same for all browsers. @kalsmic.

**Comment by PatrickMugayaJoel** [comment]
I was looking through the UI and it very nice. It has given me inspiration

**Pull request merged**
